### ISSUE TITLE
Simplify naming.

### ISSUE THREAD

**Issue by mcdonnelldean** [mcollina/hyperemitter#10]
Hey @mcollina, I wanted to get your opinion on this... The api, docs and naming schemes are inconsistent. I propose to simplify as follows:
- HyperEmitter emits `messages`
- `messages` are defined, encoded, and decoded via `messageDefinition's`
- HyperEmitter has a property `messageDefinitions` instead of `messages`
- The word `event` becomes message in all instances.
- A schema is a file that produces `messageDefinitions`
- `headers` becomes `emitterDefinitions`
- `EVENTPEER` becomes `MESSAGEPEER`

The idea is to simplify the naming globally, in docs and code, I think it will make understanding the concept simpler for people new to these concepts. I don't mind tackling this if you want? I was just thinking better to do it early rather than late.

Of course you're free to disagree :D

**Comment by mcollina** [comment]
I'm in for this, but I would stick to `EventPeer` and change `headers` to `headersDefinitions`. We can also do two protobuf files, one for `Event`and the other for `EventPeer`, as these are two completely different things. One it's used to send data and it is mandatory, while the other is just a standard message. What do you think?

**Comment by mcdonnelldean** [comment]
@mcollina Awesome. Any particular reason to stick with 'EventPeer', and 'Event' for the header messages? More just curious than having any strong opinion on them.

**Comment by mcollina** [comment]
Basically backward compatibility. Once a name is defined in protobuf, we are breaking things if we change it.

**Comment by mcdonnelldean** [comment]
@mcollina Can't argue better than that! Although we could handle that as a migration. Let me do the others on a PR anyway, and see how it all looks.

**Comment by mcdonnelldean** [comment]
@mcollina Looking at this in the next two days. I have some questions:

1: Am I to assume based on the code below that headers end up in the message collection anyway?

``` js
Object.keys(headers).forEach(function (header) {
    that.messages[header] = headers[header]
  })
```

2: If the above is true, a, I right in saying we don't actually need to collections, just to clean up the logic so we have a single merged collection?

**Comment by mcollina** [comment]
Yes, the headers ends up in the messages. No, we need two collections as
the headers collection is global, and used during initialization only.
Il giorno dom 10 mag 2015 alle 17:13 Dean McDonnell <
notifications@github.com> ha scritto:

**Comment by mcdonnelldean** [comment]
@mcollina Cool, I know what you're saying, we need to be maintaining something to merge into messages as instances are created (if multiple). I think I phrased that wrong, I should have said you don't need both collections for the instance. It's just headers on init and then merge into messages.

Cool, Do you envisage more than those two headers? I split them out as requested but if you intend to have more I was going to put them in a folder and just read everything in the folder that matched `*.proto` But if there are only ever going to be two I won't bother.

**Comment by mcollina** [comment]
I think there will be only one, as I would like to separate the core HE from the connect/listen logic. What do you think?

**Comment by mcdonnelldean** [comment]
I agree, are you thinking just two files? In the root?

**Comment by mcollina** [comment]
We can also stick them in a directory :D
Il giorno mar 12 mag 2015 alle 22:44 Dean McDonnell <
notifications@github.com> ha scritto:

**Comment by mcdonnelldean** [comment]
Will be part of #15
