### ISSUE TITLE
Are schemas shared

### ISSUE THREAD

**Issue by mcdonnelldean** [mcollina/hyperemitter#3]
If I have a schema A and Schema B on two different emitters that are connected to each other are they added together?

**Comment by mcollina** [comment]
No, it's currently like:

![don't cross the streams](http://i.giphy.com/G5q0xsHJhDhw4.gif)

We might to handle that case somehow. Any ideas? I'm not writing the schemas in the database.

**Comment by mcdonnelldean** [comment]
Ha! That's what I thought. I need to come up with some use cases for this so we can discuss them.

**Comment by mcdonnelldean** [comment]
@mcollina 

Could the emitter it's report it's schema to peers and then additively add it? I'm still not sure on this though because it would only make sense with two separate services as opposed to two horizontal ones (which would have the same schema). 

So maybe this isn't the issue, maybe the real issue is when two HyperEmitters running on separate services want interface with each other. Perhaps the right way to do this is have some sort of hand over where they are not connected the same way horizontal ones are.

My concern is we are venturing outside of the original use case. It might be more astute to build a service on top of hyper emitter that manages this and never crosses streams.

**Comment by mcollina** [comment]
I think the case we should handle is that unknown events does not throw, but are replicated nevertheless.

**Comment by mcdonnelldean** [comment]
Hmm, so only use the schema some of the time? Outside of lovely small encoding are the schema's are used for anything else?

**Comment by mcollina** [comment]
Only lovely small encoding.

**Comment by mcdonnelldean** [comment]
So if we got lovely small encoding outside of this would you drop the schema as a hard requirement? As in if you have a protobuf schema great, we will validate against that. If you want to use a different encoder that's ok too?

Personally, for my projects I would rather not use protobuff as I don't really require schema validation. This would also allow us to handle an mark non protobuff messages with an unverified flag?

**Comment by mcollina** [comment]
The thing with protobuf is that's fast, really really fast. I'm ok for an optional schema for messages, I think we should support JSON and [msgpack5](http://npm.im/msgpack5).

**Comment by mcdonnelldean** [comment]
Awesome, I think we should close this in favor of the following tickets:
- support alternate encodings
- handling multiple protobuf schemas over multiple hyper emitters.

Thoughts?

**Comment by mcollina** [comment]
Go ahead, close this one and open two new ones.

**Comment by mcdonnelldean** [comment]
Awesome
