### ISSUE TITLE
CLI protobuf schema should have a flag --schema

### ISSUE THREAD

**Issue by mcdonnelldean** [mcollina/hyperemitter#4]
Consider:

```
hypem --db db --port 1234 fixture/messages.proto
```

```
hypem --db db2 --target-port 1234 fixture/messages.proto
```

It is hard to tell what `fixute/messages.proto` is for, a simple flag would add clarity

**Comment by mcollina** [comment]
true, it was there but then I removed it somehow. I don't mind if you want to add it back :D.

**Comment by mcdonnelldean** [comment]
Awesome, I'll do this so, are you happy with --schema?

**Comment by mcollina** [comment]
You can support both :)
Il giorno mer 6 mag 2015 alle 11:13 Dean McDonnell notifications@github.com
ha scritto:

**Comment by mcdonnelldean** [comment]
Even better idea!

**Comment by mcdonnelldean** [comment]
I'll do this one before the weekend.
