### ISSUE TITLE
Not closing the stream causes issues next run

### ISSUE THREAD

**Issue by mcdonnelldean** [mcollina/hyperemitter#5]
If your code is ran but doesn't close cleanly the next run will get Connection Refused errors. To fix close and reopen a given terminal session.

**Comment by mcollina** [comment]
This is definitely not clear :). Are you referring to the `hypem` cli?

**Comment by mcdonnelldean** [comment]
@mcollina, ha sorry was adding as I found them. Ill but up a code sample in the next hour that shows it

**Comment by mcdonnelldean** [comment]
You know, I'm going to close this. It turns out I learned something new today. Ctrl-Z _suspends_ a program, not stops it. This was why I was getting issues on next run.
