### ISSUE TITLE
Handling multiple protobuf schemas over multiple connected HyperEmitters

### ISSUE THREAD

**Issue by mcdonnelldean** [mcollina/hyperemitter#6]
Given the following code:

```
var fs = require('fs')
var path = require('path')
var HyperEmitter = require('hyperemitter')

var buildDB = require('memdb')
var dbOne = buildDB('one')
var dbTwo = buildDB('two')

var getSchema = require('./getSchema')
var schemaOne = getSchema('one')
var schemaTwo = getSchema('two')

var emitterOne = new HyperEmitter(dbOne, schemaOne)
var emitterTwo = new HyperEmitter(dbTwo, schemaTwo)

emitterOne.listen(9901, function (err) {
 emitterTwo.connect(9901, '127.0.0.1', function (err) {

    // assume is in schemaOne
    var userAddedMsg = {
      id: 1,
      username: 'user'
    }

    // assume is in schemaTwo
    var userRemovedMsg = {
      id: 1
    }

    emitterOne.on('userRemoved', function (msg) {
      console.log('userRemoved: ', msg)
    })

    emitterTwo.on('userAdded', function (msg) {
      console.log('userAdded: ', msg)
    })

    emitterOne.emit('userAdded', userAddedMsg)
    emitterTwo.emit('userRemoved', userRemovedMsg)
  })
})
```

What do we think should happen? We also need to consider that some encoders may not need or use a schema and would send the messages anyway.

**Comment by mcollina** [comment]
How about a `defineMessage(name, encoderObj)` or `defineEvent(name, encoderObj)` thing? So we can get rid of the whole `schema` in `new HyperEmitter()`.

My idea is that, if a message is not known, we should emit an event in `hyper.status`, which is a stock `EventEmitter`.

**Comment by mcdonnelldean** [comment]
Ok so there are a couple of parts to your answer, let me see if I have them right:
- Emit anything we don't understand out on the `.status` emitter (we need to document this too)
- We should have a way to define messages so we can fix this at runtime if it happens
- We probably need a better interface for getting messages in than schema

Are these right?

**Comment by mcollina** [comment]
No, I think we should everything we don't understand on the main HyperEmitter, as `buffers`, which is exactly what this thing is about: moving buffers.

Than encodings will do automatic transforms from/to Buffers, for the specified messages.

Yes, let's add a `addEncoding()` method that takes care of adding that thing.

Is this all you need?

**Comment by mcdonnelldean** [comment]
Support added in #15
